[project]
name = "context-collector"
version = "0.1.0"
description = "Утилита для сборки контекста проекта в один файл"
requires-python = ">=3.8"
dependencies = [
    "pathspec>=0.12.1",
]

[project.scripts]
context-collector = "context_collector.cli:main"